---
# Supported options: 
#   sn-nature:       Style for submissions to Nature Portfolio journals
#   sn-basic:        Basic Springer Nature Reference Style/Chemistry Reference Style
#   sn-mathphys:     Math and Physical Sciences Reference Style
#   sn-aps:          American Physical Society (APS) Reference Style
#   sn-vancouver:    Vancouver Reference Style
#   sn-apa:          APA Reference Style 
#   sn-chicago:      Chicago-based Humanities Reference Style
#   default:         Default

classoptions: 
  - sn-apa      
  # - Numbered      # Optional: Use numbered references instead of namedate references (only for sn-nature, sn-basic, sn-vancouver, sn-chicago, sn-mathphys or sn-nature)
  # - referee       # Optional: Use double line spacing 
  # - lineno        # Optional: Add line numbers
  # - iicol         # Optional: Double column layour

title: "Arriaga meets Kitagawa. life expectancy decompositions including population subgroups"

titlerunning: Arriaga meets Kitagawa



authors: 
  - prefix: Dr.
    firstname: Timothy
    #particle: van 
    lastname: Riffe
    #suffix: III
    #naturename: Poet Laureate
    #degrees: MSc, PhD
    email: tim.riffe@ehu.eus
    affiliation: [1,2,3]
    corresponding: TRUE
#    equalcont: These authors contributed equally to this work.
    
  # - firstname: Second
  #   lastname: Author
  #   affiliation: 2
  #   equalcont: These authors contributed equally to this work.


affiliations:
  - number: 1
    corresponding: TRUE
    info:
      orgdiv: Department of Sociology and Social Work
      orgname: University of the Basque Country (UPV/EHU)
    address:
        street: Barrio Sarriena s/n
        city: Leioa
        postcode: 48940
        state: Bizkaia
        country: Spain
  - number: 2
    corresponding: FALSE
    info:
      orgname: Ikerbasque (Basque Foundation for Science)
  - number: 3
    corresponding: FALSE
    info:
      orgdiv: Laboratory of Population Health
      orgname: Max Planck Institute for Demographic Research
  
keywords:
  - Decomposition
  - Mortality
  - Cause of death
  - Population Structure
  - Mortality Inequalities

# pacs: 
#   jel:
#     - "D8"
#     - "H51"
#   msc:
#     - "35A01"
#     - "65L10"

# Sample for unstructured abstract 
# abstract: |
#   The abstract serves both as a general introduction to the topic and as a brief, non-technical summary of the main results and their implications. Authors are advised to check the author instructions for the journal they are submitting to for word limits and if structural elements like subheadings, citations, or equations are permitted.

# Sample for structured abstract
abstract: |
 **Background**: An Arriaga (1984) decomposition allows us to decompose differences in life expectancy into contributions due to mortality rate differences in each age. A Kitawaga (1955) decomposition allows us to decompose differences in a weighted mean into an effect from differences in structure and effects from differences in each element of the weighted value.

 **Objective:** Sometimes we would like to decompose a difference between two populations that are each composed of like-defined subpopulations. Said decomposition would produce effects for each age of each subpopulation, as well as a marginal effect of composition differences. I propose a straightforward analytic method to do this. 

 **Methods:** In short, within-subpopulation life expectancy differences can be handled by the Arriaga method. The case of weighting together the life expectancies of subpopulations by way of a composed radix can be handled using the well-known Kitagawa method. The elements of the value component of the Kitagawa method tell us how to rescale the Arriaga results specific to each subpopulation.

 **Results:** I show the proposed analytic method to be equivalent to a Horiuchi et al (2008) reframing of the same problem. Some mentionable properties: (i) There is no limit to the number of subpopulations, (ii) it is straightforward to incorporate cause-of-death information, (iii) composition is here only considered in the radix age. I currently have results for simulated mortality rates, but I promise to wrangle up an empirical application to demonstrate the method. 

 **Conclusions:** The analytic decomposition method I propose is advantageous compared to a Horiuchi method for this problem purely for reasons of computational efficiency. This method could help further disentangle the effects of mortality and composition differences in explaining or clarifying paradoxes or secular change. I promise to think further about subpopulation weighting that might occur over all ages (using prevalence information).}

bibliography: bibliography.bib

header-includes: |
  %% Per the spinger doc, new theorem styles can be included using built in style, 
  %% but it seems the don't work so commented below
  %\theoremstyle{thmstyleone}%
  \newtheorem{theorem}{Theorem}%  meant for continuous numbers
  %%\newtheorem{theorem}{Theorem}[section]% meant for sectionwise numbers
  %% optional argument [theorem] produces theorem numbering sequence instead of independent numbers for Proposition
  \newtheorem{proposition}[theorem]{Proposition}%
  %%\newtheorem{proposition}{Proposition}% to get separate numbers for theorem and proposition etc.

  %% \theoremstyle{thmstyletwo}%
  \theoremstyle{remark}
  \newtheorem{example}{Example}%
  \newtheorem{remark}{Remark}%

  %% \theoremstyle{thmstylethree}%
  \theoremstyle{definition}
  \newtheorem{definition}{Definition}%
  \usepackage{amsmath}
output: rticles::springer_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      out.extra = "")  # This forces knitr to label all figures.
```

# Background

An @arriaga1984measuring decomposition allows us to decompose changes in life expectancy into contributions due to mortality changes in different ages. The method was designed to be practical, and framed in terms of age lifetable columns expressed in discrete age groups. A well-known property of the method is that mortality changes in different ages need not be proportional. Derived contributions also sum exactly to the observed life expectancy difference. A not-well-known property of the method is that it is asymmetrical, in the sense that the absolute values of age-specific contributions depend on whether we compare population 1 with 2, or population 2 with 1. A further property of the method is that it is designed to work with homogeneous populations, meaning that populations 1 and 2 are each homogeneous, in the sense that each is expressed with only one lifetable.

A @kitagawa1955components decomposition allows us to decompose differences in a weighted mean due to differences in weights (structure) and differences in the value being weighted (often rates, but in our case life expectancies). This widely-used decomposition method is well-known to be exact in that the resulting structure and value components sum exactly to the observed difference in weighted means. The individual elements (ages, or life expectancies for us) of the value being weighted have identifiable effects. It is not well-known that the individual elements of the structure component do not have identifiable effects. Rather, the structure effects should be summed to a a marginal effect due to differences in structure.

# Introduction
A demographer might like to decompose a difference in life expectancy between two populations (or one population at two times) that are each composed of like-defined subpopulations. For example, life expectancy in France versus Spain, each with education-specific subpopulations, or a national life expectancy calculated as the weighted average of its regions at two points in time. In such situations, a decomposition would ideally tell us the contribution to the difference in overall life expectancy due to rate differences in each age in each subpopulation, and also separate an effect due to overall compositional change. In this paper, I would like to propose a straightforward analytic method to decompose in this way. In short, within-subpopulation life expectancy differences can be handled by the Arriaga method. The case of weighting together the life expectancies of subpopulations by way of a composed radix can be handled using the well-known Kitagawa method. The elements of the value component of the Kitagawa method tell us how to rescale the Arriaga results specific to each subpopulation so as to isolate the age-subpopulation-specific effects on the overall life expectancy difference. I will justify this rescaling, and show that the results of this procedure are fully consistent with the results of a @horiuchi2008decomposition reframing of the problem.

# Method

## Notation

In formulas, we use the following variables and scripting, most of which are lifetable columns:

```{=tex}
\begin{itemize}

\item{$\ell(a)$} lifetable survivorship at exact age $a$.

\item{${}_nL_a$} lifetable person years lived in the interval $[a,a+n)$.

\item{$T_a$} total lifetable person years lived beyond age $a$.

\item{$e_a$} remaining life expectancy at exact age $a$.

\item{$\pi^s$} the initial population fraction for subgroup $s$ at the initial age. 
\end{itemize}
```
We also use the superscript $s$ to index subpopulations comprising the total population, and the superscript $t$ to index time points, or some other way of differentiating the total population. The index $e^{s,t}_0$ reads as "life expectancy at birth for subpopulation $s$ at time $t$", e.g. $e^{low, 1990}_0$ could be the life expectancy in 1990 of a low education group. 

## Averaging life expectancy

There are two major approaches to producing average life expectancy for a total population composed of subgroups, as @vaupel2002life points out. One could derive the average mortality rate in each age by summing the respective deaths and exposures from subpopulations and then deriving the rate, as the Human Mortality Database @wilmoth2021methods does, then recalculate the total population lifetable from these. This is what Vaupel called _current rates_ approach, which ignores even controllable heterogeneity. The other approach derives subgroup-specific lifetables, then weights life expectancies together according to an initial mixing composition in order to arrive at the total life expectancy. This is Vaupel's _current conditions_ approach, at least in part. This second approach is what is often done in multistate models (cite), but also sometimes with standard lifetables, for example, when doing between-within decompositions of variance or other similar summary measures. Our decomposition method deals with this second case, specifically, we have:

\begin{equation}
\label{eq_avg}
e_0 = \sum_s \pi^s \cdot e_0^s \quad \textrm{,}
\end{equation}

\noindent where the $S$ total subgroup fractions comprise a mixing distribution, $1 = \sum_s \pi^s$. 

## Kitagawa decomposition 
Eq \eqref{eq_avg} treats the total life expectancy as a weighted average, which means we can decompose a change over time in $e_0$ ($\Delta = e_0^2 - e_o^1$) exactly using the formulas from @kitagawa1955components. Specifically, eq \eqref{eq_kit_comp} gives an overall effect of changes in composition:

\begin{equation}
\label{eq_kit_comp}
\Delta^\text{composition} = \sum_s \left(\pi^{s,t2}- \pi^{s,t1}\right) \cdot \frac{e_0^{s,t1} + e_0^{s,t2}}{2} \quad \textrm{,}
\end{equation}

This result is widely known, but many are unaware that the composition effect should be summed like this, since the group-specific composition (structure) effects are not well-identified. Eq \eqref{eq_kit_e0} gives the subgroup-specific effects from changes in life expectancy:

\begin{equation}
\label{eq_kit_e0}
\Delta^{e_0^s\text{~change}} = \left(e_0^{s,t2} - e_0^{s,t1}\right) \cdot \frac{\pi^{s,t1} + \pi^{s,t2}}{2}\quad \textrm{.}
\end{equation}

Eq \eqref{eq_kit_sum} says that the overall change in life expectancy is the sum of (i) a single component that captures the effect of composition change and (ii) a set of components describing the effect on overall life expectancy from each group's specific life expectancy change. This second effect could just as well be called the _rate_ effect, since each life expectancy is fully determined by mortality rates. 

\begin{equation}
\label{eq_kit_sum}
\Delta = \Delta^\text{composition}  + \sum_s \Delta^{e_0^s\text{~change}}
\end{equation}

## Symmetrical Arriaga decomposition
The above-mentioned _rate_ effect can be conceived of as the _net_ effect on total life expectancy change of the age-specific effects within subgroups, as isolated by the many varieties of life expectancy decompositions. In this case, it does not matter much which method we choose to derive age-specific effects for subgroup-specific changes in life expectancy. The @arriaga1984measuring decomposition approach is popular in part because it is efficient, analytic, and sums exactly to the observed life expectancy difference. This method can be implemented in a number of relevant ways, per Riffe et. al. (2024), from which we here consider only _symmetrical_ Arriaga decomposition. This implies following the original formulas twice, once in each direction, and averaging the sign-adjusted results. We repeat this exercise for each subgroup to decompose group-specific changes in life expectancy (hence the $^s$ on everything):

\begin{align}
\label{eq_kit_e0}
\Delta^s &= e_0^{s,2} - e_0^{s,1}  \\
 &= \sum _x {}_n\Delta_x^s \quad \textrm{,}\nonumber 
\end{align}

\noindent where $\Delta^s$ is the subgroup-specific ($s$) difference in life expectancy being decomposed, and it is composed of age-specific contributions, $\overrightarrow{{}_n\Delta_x^s}$ or $\overleftarrow{{}_n\Delta_x^s}$ depending on whether we decompose forward in time or backward, respectively (Riffe et. al., 2024). The forward age-specific values $\overrightarrow{{}_n\Delta_x^s}$ can be calculated following Arriaga's decomposition method following eq \eqref{eq_arriaga1}, consistent with @arriaga1984measuring or the presentation in @preston2000demography. I use a lifetable radix of 1, meaning $\ell_0 = 1$, to reduce the formula slightly. 

\begin{equation}
\label{eq_arriaga1}
 \overrightarrow{{}_n\Delta_x^s} = \begin{cases}\ell_x^{s,1} \cdot \left( \frac{{}_nL_x^{s,2}}{\ell_x^{s,2}} - \frac{{}_nL_x^{s,1}}{\ell_x^{s,1}}\right)+T_{x+n}^{s,2}\cdot\left(\frac{\ell_x^{s,1}}{\ell_x^{s,2}} - \frac{\ell_{x+n}^{s,1}}{\ell_{x+n}^{s,2}}\right)  & \text{$ \forall x < \omega$}  \\
  \ell_\omega ^{s,1} \cdot (e_\omega^{s,2} -e_\omega^{s,1} ) & \text{$\forall x = \omega $}
  \end{cases}
\end{equation}

Equation \eqref{eq_arriaga1} is the first pass of our symmetrical decomposition, and \eqref{eq_arriaga2} is the second pass, identical except all time superscripts are swapped.
 
\begin{equation}
\label{eq_arriaga2}
 \overleftarrow{{}_n\Delta_x^s} = \begin{cases}\ell_x^{s,2} \cdot \left( \frac{{}_nL_x^{s,1}}{\ell_x^{s,1}} - \frac{{}_nL_x^{s,2}}{\ell_x^{s,2}}\right)+T_{x+n}^{s,1}\cdot\left(\frac{\ell_x^{s,2}}{\ell_x^{s,1}} - \frac{\ell_{x+n}^{s,2}}{\ell_{x+n}^{s,1}}\right)  & \text{$ \forall x < \omega$}  \\
  \ell_\omega ^{s,2} \cdot (e_\omega^{s,1} -e_\omega^{s,2} ) & \text{$\forall x = \omega $}
  \end{cases}
\end{equation}

Importantly,

\begin{align}
\label{eq_sum2}
 -\Delta^s &= \sum_x \overleftarrow{{}_n\Delta_x^s} \\
 &= e_0^1 - e_0^2 \nonumber
\end{align}

Then our symmetrical estimate of ${}_n\Delta_x^s$ is just the average of these:

\begin{equation}
\label{eq_arriaga3}
{}_n\Delta_x^s = \frac{\left(\overrightarrow{{}_n\Delta_x^s} -  \overleftarrow{{}_n\Delta_x^s}\right)}{2}
\end{equation}

Repeat the above to derive ${}_n\Delta_x^s$ for each within-subpopulation comparison.

## Rescale Arriaga results

The age-specific quantities ${}_n\Delta_x^s$ derived from eq \eqref{eq_arriaga3} are on the scale of subgroup-specific life expectancy changes. To know the net impact of ${}_n\Delta_x^s$ on overall life expectancy change we rescale per eq \eqref{eq_rescale} to match the effect sizes from eq \eqref{eq_kit_e0}

\begin{equation}
\label{eq_rescale}
{}_n\Delta_x^{s,\text{net}} = \Delta^{e_0^s\text{~change}} \cdot \frac{{}_n\Delta_x^s}{\Delta^s} \quad \mathrm{.}
\end{equation}

With eqs \eqref{eq_kit_comp} and \eqref{eq_rescale}, we have all elements of the present decomposition:

\begin{equation}
\label{eq_full}
\Delta = \Delta^\text{composition} + \sum_s \sum_x {}_n\Delta_x^{s,\text{net}}
\end{equation}


\backmatter

\bmhead{Supplementary information}

If your article has accompanying supplementary file/s please state so here.


\bmhead{Acknowledgments}

Thanks to Michael Lachanski for posing to me the question that led to the solution I present here, to Jonas Schoeley for first bringing the composition problem with the Kitagawa method to my attention, and to the MPIDR Laboratory of Population Health for posing assorted questions in September 2023 that got me thinking in these lines. 

# Declarations {.unnumbered}

Some journals require declarations to be submitted in a standardised format. Please check the Instructions for Authors of the journal to which you are submitting to see if you need to complete this section. If yes, your manuscript must contain the following sections under the heading 

## Funding
This work was financed in part by grant nr SR22-00502 from _la Caixa Foundation_ and grant nr PID2022-142762OA-I00 from the Spanish _Ministerio de Ciencia e Innovación_.

## Conflict of interest
The author declares no conflict of interest

## Availability of data and materials
All data are ___

## Code availability
All code used here is available in an open `GitHub` repository \url{https://github.com/timriffe/arriagakitagawa}

::: {.appendices latex="true"}
# Section title of first appendix {#secA1}

An appendix contains supplementary information that is not an essential part of the text itself but which may be helpful in providing a more comprehensive understanding of the research problem or it is information that is too cumbersome to be included in the body of the paper.

For submissions to Nature Portfolio Journals please use the heading "Extended Data".
:::
